FROM jenkins/jenkins
# if we want to install via apt
USER root
RUN apt-get update && apt-get install -y maven && (curl -sSL https://get.docker.com/ | sh)
# drop back to the regular jenkins user - good practice
USER jenkins